### ISSUE TITLE
V1 Roadmap

### ISSUE THREAD

**Issue by evillt** [evillt/elv-form#1]
## Basic

- [ ] Support all `el-form` props

### slots

- [ ] Figure out a way to supported / ~~or not~~.

### props?

If only support `props`, then how about the `native-attrs` when using native component (e.g. `<div>`)

## Documentation

- [ ] A site or just in Readme
